### ISSUE TITLE
Crashes System on Ubuntu 20, Ubuntu 22 and Amazon Linux 2

### ISSUE THREAD

**Issue by loco-avenger** [ihorlv/db1000nX100#4]
I'm using docker to run and pull the latest db1000nX100.  It consistently crashes the entire system on Ubuntu 20, Ubuntu 22, or Amazon Linux 2 instances.   I'm using AWS for Ubuntu 20 and Amazon Linux 2, but have a local Ubuntu 22 virtual machine that crashes too.

This is a great enhancement to db1000n and I think it is a great program overall that is awesome.  I just restart the Linux instances and it runs again for a few minutes just fine.   However, it does crash the system and I would be happy to provide more details if you're interested.   

This is the last line in the logfile located at: put-your-ovpn-files-here/db1000nX100-log.txt.  However, I've seen the last line filled with null data.

```
2022-08-04 00:45:38 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
2022-08-04 00:45:38 TLS Error: TLS handshake failed
2022-08-04 00:45:38 SIGUSR1[soft,tls-error] received, process restarting
2022-08-04 00:45:38 Restart pause, 5 second(s)
VPN Timeout

OpenVpnConnection terminate PGID -25503
OpenVpnConnection kill PGID -25503
```

**Comment by ihorlv** [comment]
Hi. Thank you for your help. Please, provide some more information:
1. How the crash of the entire system on Ubuntu looks like?
2. Can you provide the complete db1000nX100-log.txt
If you have some security concerns to attach it here, you may send it to my email ukrainebattle2022@gmail.com

**Comment by loco-avenger** [comment]
I believe this has been fixed.   It must have been a problem between Docker and the Linux kernel when the VPN processes were killed off.   Both Ubuntu and Amazon kernels seems to have been updated, and I can no longer cause the system to crash.   So, I think this can be closed.

If others have this problem on Linux versions, try updating the kernel and use Docker from the Docker site instead of the default Docker install.

Thank you again for a fantastic program, I've been using a lot of ovpn files from IPVanish and it works perfectly.   Slava Ukraini and thanks again!
